name: Java Spring Boot Pipeline (via Dagger)

on:
  push:
    branches: [ main, master, 2-bg-au-tremplin, dagger-graphql]
  pull_request:
    branches: [ main, master ]

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dagger CLI (v0.19.1)
        run: |
          curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.19.1 sudo BIN_DIR=/usr/local/bin sh
          dagger version

      - name: Setup Permissions
        run: chmod +x ci/run-pipeline.sh

      - name: Build
        run: ./ci/run-pipeline.sh build

      - name: Unit Tests
        run: ./ci/run-pipeline.sh unit-tests

      - name: Integration Tests
        run: ./ci/run-pipeline.sh integration-tests

      - name: Sonar Analysis
        run: ./ci/run-pipeline.sh sonar

      - name: Deploy
        run: ./ci/run-pipeline.sh deploy